name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.1.2
  google_fonts: ^6.2.1 
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.0
  fluttertoast: ^8.2.10
  # firebase_core_platform_interface: ^5.4.0
  # firebase_messaging: ^15.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
