// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJOw_IzLtIVcP92SBUvs2iFKFdkueXHdM',
    appId: '1:506712724047:web:96c26c19c48b7ca222503a',
    messagingSenderId: '506712724047',
    projectId: 'todoapp-c12ce',
    authDomain: 'todoapp-c12ce.firebaseapp.com',
    storageBucket: 'todoapp-c12ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbzmjrdz_s6j1KJQG3qY7GUpT-05zTN2w',
    appId: '1:506712724047:ios:a4c489cc798bc6a822503a',
    messagingSenderId: '506712724047',
    projectId: 'todoapp-c12ce',
    storageBucket: 'todoapp-c12ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbzmjrdz_s6j1KJQG3qY7GUpT-05zTN2w',
    appId: '1:506712724047:ios:a4c489cc798bc6a822503a',
    messagingSenderId: '506712724047',
    projectId: 'todoapp-c12ce',
    storageBucket: 'todoapp-c12ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJOw_IzLtIVcP92SBUvs2iFKFdkueXHdM',
    appId: '1:506712724047:web:040f10b686a4555822503a',
    messagingSenderId: '506712724047',
    projectId: 'todoapp-c12ce',
    authDomain: 'todoapp-c12ce.firebaseapp.com',
    storageBucket: 'todoapp-c12ce.firebasestorage.app',
  );
}
